---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bpexproc/bpexpro/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R deploy $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp vite-plugin-bpexch-proxy.js $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp capacitor.config.json $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
